on: [push]
jobs:
  build:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
    - name: trigger job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.sdpmlab.org/"
        user: "Jacob"
        token: ${{secrets.TOKEN}}
        job: "tcse2023-ja4321cob"
